## Digilent Arty A7-100T (XC7A100T-1CSG324C)
## Pins taken from the official Digilent master XDC (Arty-A7-100-Master.xdc).

## ---------------------------------------------------------------- configuration
set_property CFGBVS VCCO        [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

## ---------------------------------------------------------------------- clock
set_property -dict { PACKAGE_PIN E3 IOSTANDARD LVCMOS33 } [get_ports { CLK100MHZ }]
create_clock -name sys_clk -period 10.000 -waveform {0 5} [get_ports { CLK100MHZ }]

## The 75 MHz core clock is generated by the MMCM; Vivado derives it
## automatically from CLKOUT0, so it must NOT be declared with create_clock here.

## ---------------------------------------------------------------------- reset
## ck_rst is the board reset pushbutton, active low.
set_property -dict { PACKAGE_PIN C2 IOSTANDARD LVCMOS33 } [get_ports { ck_rst }]

## ----------------------------------------------------------------------- LEDs
set_property -dict { PACKAGE_PIN H5  IOSTANDARD LVCMOS33 } [get_ports { led[0] }]
set_property -dict { PACKAGE_PIN J5  IOSTANDARD LVCMOS33 } [get_ports { led[1] }]
set_property -dict { PACKAGE_PIN T9  IOSTANDARD LVCMOS33 } [get_ports { led[2] }]
set_property -dict { PACKAGE_PIN T10 IOSTANDARD LVCMOS33 } [get_ports { led[3] }]

## ------------------------------------------------------------- USB-UART bridge
## Naming is from the HOST's point of view: uart_rxd_out is what the FPGA DRIVES
## and the PC receives.  Getting this backwards is the classic Arty UART bug.
set_property -dict { PACKAGE_PIN D10 IOSTANDARD LVCMOS33 } [get_ports { uart_rxd_out }]

## ------------------------------------------------------------------- timing IO
## These are all asynchronous to any external clock: the LEDs drive a human eye
## and the reset is a mechanical button.  Constraining them would be meaningless,
## so cut them explicitly rather than leaving them unconstrained and noisy.
set_false_path -from [get_ports ck_rst]
set_false_path -to   [get_ports { led[*] }]

## The UART TX pin is genuinely timed logic internally, but the receiver
## resynchronises to the start bit, so its pad delay is irrelevant.
set_false_path -to [get_ports uart_rxd_out]

## ------------------------------------------------------------- clock relationship
## sys_clk (100 MHz) and the MMCM's 75 MHz output are physically related, but no
## DATA crosses between them in this design: the only crossings are the two reset
## synchronisers, which are asynchronous by construction (async assert, sync
## release).  Declaring the groups asynchronous stops Vivado from timing paths
## that do not exist.  Revisit this the moment real data crosses domains.
set_clock_groups -asynchronous \
  -group [get_clocks sys_clk] \
  -group [get_clocks -of_objects [get_pins u_clkgen/u_mmcm/CLKOUT0]]
