#!/usr/bin/env python3
"""
Choose MMCM parameters for a target core frequency and emit them as macros.

Why this is generated rather than typed in three places: the A12 Fmax search
sweeps the core clock, and THREE things have to move together -- the MMCM
divider, the UART baud divisor (which is CLK_HZ/BAUD inside rvntt_uart_tx), and
whatever the timing report is compared against.  Typing them separately is how
you end up measuring 95 MHz and decoding the UART at the wrong baud, then
blaming the serial cable.  One script writes all of them from one number.

Note on the plan's "constrain the target period T in the XDC": with an
MMCM-generated clock you do not, and must not, write a create_clock for the core
domain -- Vivado derives the generated clock from the MMCM's own parameters, and
a competing create_clock would either be ignored or silently override the real
relationship.  The MMCM divider IS the constraint.  So T is set here, Vivado
derives it, and fpga/scripts/build_soc.tcl asserts afterwards that the period
Vivado actually derived matches the one requested -- which is the check that
keeps this honest.

Artix-7 -1 speed grade: VCO must land in 600-1200 MHz.  CLKFBOUT_MULT_F and
CLKOUT0_DIVIDE_F move in steps of 0.125, so the reachable frequencies near
100 MHz are about 1.4 MHz apart; the search reports the achieved value, never
the requested one.
"""
import argparse, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT  = os.path.join(ROOT, "fpga", "generated")

FIN_MHZ  = 100.0
VCO_MIN  = 600.0
VCO_MAX  = 1200.0


def solve(target_mhz):
    """Best (mult, divclk, out_div, achieved_mhz) for `target_mhz`."""
    best = None
    for m8 in range(int(2.0 * 8), int(64.0 * 8) + 1):          # 0.125 steps
        mult = m8 / 8.0
        vco = FIN_MHZ * mult                                    # DIVCLK_DIVIDE = 1
        if vco < VCO_MIN or vco > VCO_MAX:
            continue
        for o8 in range(int(1.0 * 8), int(128.0 * 8) + 1):
            odiv = o8 / 8.0
            f = vco / odiv
            err = abs(f - target_mhz)
            # Tie-break on the lower VCO: less jitter, and it keeps the chosen
            # solution stable across runs instead of flipping between equals.
            key = (round(err, 9), vco)
            if best is None or key < best[0]:
                best = (key, mult, 1, odiv, f)
    if best is None:
        raise SystemExit("no MMCM solution for %.3f MHz" % target_mhz)
    _, mult, divclk, odiv, f = best
    return mult, divclk, odiv, f


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mhz", type=float, default=75.0,
                    help="target core frequency in MHz")
    ap.add_argument("--baud", type=int, default=115200)
    ap.add_argument("--out", default=os.path.join(OUT, "soc_clk.svh"))
    a = ap.parse_args()

    mult, divclk, odiv, f = solve(a.mhz)
    hz = int(round(f * 1e6))
    period_ns = 1000.0 / f

    divisor = hz // a.baud
    # UART tolerates roughly 2% accumulated over 10 bit times.  Refuse rather
    # than emit a header that produces garbage on the wire at some frequencies
    # and not others -- a silent baud error is very hard to tell from a broken
    # UART.
    actual_baud = hz / divisor if divisor else 0
    err_pct = abs(actual_baud - a.baud) / a.baud * 100.0 if divisor else 100.0
    if divisor < 4 or err_pct > 1.0:
        print("baud divisor %d gives %.1f baud (%.3f%% error) -- too far from %d"
              % (divisor, actual_baud, err_pct, a.baud), file=sys.stderr)
        return 1

    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w") as fh:
        fh.write("// GENERATED by fpga/scripts/gen_soc_clk.py -- do not edit.\n")
        fh.write("// target %.3f MHz -> achieved %.6f MHz (period %.6f ns)\n"
                 % (a.mhz, f, period_ns))
        fh.write("`define SOC_CORE_HZ    %d\n"      % hz)
        fh.write("`define SOC_MMCM_MULT  %.3f\n"    % mult)
        fh.write("`define SOC_MMCM_DIV   %d\n"      % divclk)
        fh.write("`define SOC_MMCM_OUT   %.3f\n"    % odiv)
        fh.write("`define SOC_BAUD       %d\n"      % a.baud)

    print("target %.3f MHz -> M=%.3f D=%d O=%.3f  VCO=%.1f MHz  achieved %.6f MHz"
          % (a.mhz, mult, divclk, odiv, FIN_MHZ * mult / divclk, f))
    print("period %.6f ns   baud divisor %d -> %.1f baud (%.3f%% error)"
          % (period_ns, divisor, actual_baud, err_pct))
    print("wrote %s" % a.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
