#!/usr/bin/env python3
"""
Generate the BRAM init image and its expected checksum, from the same data in
the same script so the two can never disagree.

Outputs:
  fpga/generated/bram_init.mem       -- $readmemh image, one 32-bit word per line
  fpga/generated/bram_expected.svh   -- localparam with the expected checksum
"""
import argparse, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT  = os.path.join(ROOT, "fpga", "generated")


def word(i: int) -> int:
    """
    A deliberately non-trivial pattern.  A constant or a plain ramp would still
    checksum correctly if the address generator were broken (e.g. reading the
    same address 256 times), so mix the address in non-linearly.
    """
    x = (i * 0x9E3779B9) & 0xFFFFFFFF      # golden-ratio multiplier
    x ^= (x >> 16)
    x = (x * 0x85EBCA6B) & 0xFFFFFFFF
    x ^= (x >> 13)
    return x & 0xFFFFFFFF


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--depth", type=int, default=256)
    a = ap.parse_args()

    os.makedirs(OUT, exist_ok=True)
    words = [word(i) for i in range(a.depth)]

    # Checksum: running sum with a rotate, so word ORDER matters.  A plain XOR or
    # sum would pass even if the readback returned the words in the wrong order.
    acc = 0
    for w in words:
        acc = ((acc << 1) | (acc >> 31)) & 0xFFFFFFFF   # rotate left 1
        acc = (acc + w) & 0xFFFFFFFF

    mem = os.path.join(OUT, "bram_init.mem")
    with open(mem, "w") as f:
        for w in words:
            f.write("%08x\n" % w)

    svh = os.path.join(OUT, "bram_expected.svh")
    with open(svh, "w") as f:
        f.write("// GENERATED by fpga/scripts/gen_bram_init.py -- do not edit.\n")
        f.write("localparam int          BRAM_DEPTH    = %d;\n" % a.depth)
        f.write("localparam logic [31:0] BRAM_EXPECTED = 32'h%08X;\n" % acc)

    print("wrote %s (%d words)" % (mem, a.depth))
    print("wrote %s (expected checksum 0x%08X)" % (svh, acc))
    return 0


if __name__ == "__main__":
    sys.exit(main())
