#!/usr/bin/env python3
"""
Generate the TIER1 NTT backend for ML-KEM-768.

Two things are generated rather than written by hand:

  * The zeta table.  Plan B0 is explicit -- do not hand-copy it.  The values
    come from model/ntt_ref.py, which derives them from the root of unity, and
    this script additionally parses the literal array out of the pristine
    reference ntt.c and refuses to emit anything unless the two agree
    element for element.  A silent transcription error in this table is the
    kind of bug that produces a KAT failure with no useful localisation.

  * ntt() / invntt() / basemul(), expressed purely in terms of the Xkntt
    instructions from sw/include/xkntt.h.  These are the same loop structures
    as the reference, restructured so each butterfly is one instruction.

The reference's own ntt.c is not compiled in this backend; the linker takes
these definitions instead.  Everything else in the reference is untouched.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "model"))
import ntt_ref as NR                                           # noqa: E402

REF_NTT_C = os.path.join(ROOT, "toolchain", "kyber", "ref", "ntt.c")


def reference_zetas():
    """Parse `const int16_t zetas[128] = { ... };` out of the pristine reference."""
    text = open(REF_NTT_C).read()
    m = re.search(r"const int16_t zetas\[128\]\s*=\s*\{(.*?)\};", text, re.S)
    if not m:
        raise SystemExit(f"could not find the zeta array in {REF_NTT_C}")
    return [int(v) for v in re.findall(r"-?\d+", m.group(1))]


BODY = r'''/*
 * GENERATED by sw/kyber/gen_ntt_tier1.py -- do not edit.
 *
 * ML-KEM-768 NTT, inverse NTT and base multiplication built entirely from the
 * Xkntt Tier-1 instructions.  Replaces the reference ntt.c at link time; every
 * other reference source is compiled unmodified, so a KAT failure here can only
 * come from this file or from the instructions themselves.
 */
#include <stdint.h>
#include "params.h"
#include "ntt.h"
#include "reduce.h"
#include "xkntt.h"

const int16_t zetas[128] = {
%(zetas)s
};

/*
 * One kbfct per Cooley-Tukey butterfly.  The reference does
 *     t = fqmul(zeta, r[j+len]);  r[j+len] = r[j] - t;  r[j] = r[j] + t;
 * which is exactly kbfct's definition once the pair is packed with the
 * low-index coefficient in the low half.
 */
void ntt(int16_t r[256])
{
  unsigned int len, start, j, k = 1;
  for (len = 128; len >= 2; len >>= 1) {
    for (start = 0; start < 256; start = j + len) {
      uint32_t z = (uint32_t)(uint16_t)zetas[k++];
      for (j = start; j < start + len; j++) {
        uint32_t res = xk_kbfct(xk_pack(r[j], r[j + len]), z);
        r[j]       = xk_lo(res);
        r[j + len] = xk_hi(res);
      }
    }
  }
}

/*
 * One kbfgs per Gentleman-Sande butterfly, then one kmm per coefficient for
 * the final mont^2/128 scaling.  kbfgs folds the barrett_reduce on the sum and
 * the fqmul on the difference into a single instruction.
 */
void invntt(int16_t r[256])
{
  unsigned int start, len, j, k = 127;
  const uint32_t f = (uint32_t)(uint16_t)%(f)d;   /* mont^2 / 128 */

  for (len = 2; len <= 128; len <<= 1) {
    for (start = 0; start < 256; start = j + len) {
      uint32_t z = (uint32_t)(uint16_t)zetas[k--];
      for (j = start; j < start + len; j++) {
        uint32_t res = xk_kbfgs(xk_pack(r[j], r[j + len]), z);
        r[j]       = xk_lo(res);
        r[j + len] = xk_hi(res);
      }
    }
  }

  for (j = 0; j < 256; j++)
    r[j] = (int16_t)xk_kmm((uint32_t)(uint16_t)r[j], f);
}

/* kbmul0 produces c0 (needs the zeta, hence R4); kbmul1 produces c1. */
void basemul(int16_t r[2], const int16_t a[2], const int16_t b[2], int16_t zeta)
{
  uint32_t pa = xk_pack(a[0], a[1]);
  uint32_t pb = xk_pack(b[0], b[1]);
  r[0] = (int16_t)xk_kbmul0(pa, pb, (uint32_t)(uint16_t)zeta);
  r[1] = (int16_t)xk_kbmul1(pa, pb);
}
'''


def main():
    ref = reference_zetas()
    if len(ref) != 128:
        raise SystemExit(f"reference zeta array has {len(ref)} entries, expected 128")
    if ref != NR.ZETAS:
        bad = [i for i in range(128) if ref[i] != NR.ZETAS[i]]
        raise SystemExit(f"zeta mismatch at indices {bad[:8]}: "
                         f"reference {ref[bad[0]]} vs model {NR.ZETAS[bad[0]]}")

    rows = []
    for i in range(0, 128, 8):
        rows.append("  " + ", ".join(f"{v:5d}" for v in NR.ZETAS[i:i+8]) + ",")
    text = BODY % {"zetas": "\n".join(rows).rstrip(","), "f": NR.F_INVNTT}

    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "build", "ntt_tier1.c")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write(text)
    print(f"generated {out} (zetas verified against {os.path.relpath(REF_NTT_C, ROOT)})")


if __name__ == "__main__":
    main()
