#!/usr/bin/env python3
"""
Drive riscv-formal over rvntt_core.

riscv-formal bounded-model-checks the core against a formal model of the ISA
through the RVFI port rvntt_rvfi.sv exposes.  genchecks.py must run from
`<riscv-formal>/cores/<name>/`, and the checkout is gitignored, so the
configuration is generated into it from the template below; --rtl-dir points
the file list at a mirrored tree.

Depth 14: riscv-formal constrains `reset` to step 0 only and the first
instruction retires at cycle 5, so a check at cycle N sees at most N-4
retirements.  The deepest dependency a check must reach is a register
dependency at distance 3 (the register file's write-through) with a load-use
stall and a two-cycle flush in the window, i.e. the 8th cycle after the first
retirement.  BMC time grows superlinearly with depth, so it is not larger.

Not checked, stated rather than discovered:

  * `dmem` and the `bus_*` family need a memory model in the wrapper, which
    leaves dmem_rdata unconstrained on purpose.  Memory consistency is
    covered by cosimulation and riscv-tests against a real RAM.
  * `ill`, `csrw` and `csr_ill`: riscv-formal has no model for Zicsr, ECALL,
    EBREAK, MRET or FENCE, and `ill` would demand that `csrr` trap.  The CSR
    file is covered by formal_csr, rv32mi-p and RISCOF's privilege suite.
  * What the M instructions compute.  rvntt_muldiv's arithmetic is abstracted
    to a free value (RVNTT_ABSTRACT_MULDIV); its sequencer is not, so every
    stall, bubble and retirement time is the real design's.  The arithmetic
    is covered by tb/formal/rvntt_muldiv.sby, rv32um and cosimulation.
"""
import argparse
import concurrent.futures
import os
import re
import shutil
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RF = os.path.join(ROOT, "toolchain/riscv-formal")
CORE_NAME = "rvntt"
# The core directory is settable (--core-name) because the mutation harness
# runs mutations in parallel, each against its own mirrored tree.
CORE_DIR = os.path.join(RF, "cores", CORE_NAME)   # rebound by --core-name
WRAPPER = os.path.join(ROOT, "tb/formal/rvntt_rvfi_wrapper.sv")

# rv32i_pkg must precede anything whose port list uses its types.
RTL = [
    "rtl/core/rv32i_pkg.sv",
    "rtl/core/rvntt_decode.sv",
    "rtl/core/rvntt_alu.sv",
    "rtl/core/rvntt_immgen.sv",
    "rtl/core/rvntt_regfile.sv",
    "rtl/core/rvntt_forward.sv",
    "rtl/core/rvntt_hazard.sv",
    "rtl/core/rvntt_branch.sv",
    "rtl/core/rvntt_csr.sv",
    "rtl/core/rvntt_muldiv.sv",
    "rtl/core/rvntt_bitmanip.sv",
    "rtl/core/rvntt_bpred.sv",
    # rvntt_entropy with STUB=1, as everywhere except the bitstream: Yosys
    # cannot represent the ring oscillator's combinational loop.
    "rtl/core/rvntt_seed.sv",
    "rtl/core/rvntt_entropy.sv",
    "rtl/core/rvntt_entropy_health.sv",
    "rtl/core/rvntt_rvfi.sv",
    "rtl/core/rvntt_core.sv",
]

DEPTH = 14

# Liveness is the one check whose depth is set by a latency rather than a
# dependency distance: "if instruction N retires at the trigger cycle, N+1 has
# retired by the check cycle", so the window holds the worst gap between two
# consecutive retirements -- one cycle, plus two for a flush, plus one for a
# load-use stall, plus 33 for a DIV occupying EX for 34.  9 + 37 = 46.
# Affordable only because RVNTT_ABSTRACT_MULDIV is set.
LIVENESS_DEPTH = 46

# riscv-formal ships bundles for RV32I + Zba + Zbb + Zbs (isa_rv32ib.txt) and
# for Zbkb (isa_rv32iZbkb.txt) but none for the union, and genchecks.py takes
# exactly one bundle name, so the union is generated here on every run.  The
# name must parse as an ISA string (^rv(\d+)([ie])([a-v]*)(_?[SZX]\w+)?$).
# M's models are still not included: against RVNTT_ABSTRACT_MULDIV they would
# be vacuous, and against the concrete multiplier they do not converge.
ISA_BUNDLE = "rv32ib_Zbkb"
ISA_PARTS  = ("rv32ib", "rv32iZbkb")


def write_isa_bundle():
    """Generate insns/isa_rv32ib_Zbkb.txt as the union of its two parts.
    Written atomically (write-then-rename), since parallel invocations share
    the path."""
    insns_dir = os.path.join(RF, "insns")
    union = []
    for part in ISA_PARTS:
        src = os.path.join(insns_dir, "isa_%s.txt" % part)
        if not os.path.exists(src):
            raise SystemExit(
                "riscv-formal has no insns/isa_%s.txt -- the checkout is older "
                "than the B models this step needs" % part)
        with open(src) as f:
            union += [l.strip() for l in f if l.strip()]
    union = sorted(set(union))
    dst = os.path.join(insns_dir, "isa_%s.txt" % ISA_BUNDLE)
    tmp = "%s.tmp.%d" % (dst, os.getpid())
    with open(tmp, "w") as f:
        f.write("\n".join(union) + "\n")
    os.replace(tmp, dst)
    return len(union)


CHECKS_CFG = """# GENERATED by tb/formal/run_riscv_formal.py -- edit that, not this.

[options]
isa {isa}
mode bmc
# bitwuzla rather than the genchecks default of boolector, as in run_formal.py.
solver bitwuzla

# Columns are [reset_cycles] [trig_cycle] check_cycle; see the module docstring
# for where 14 comes from.
[depth]
insn                {depth}
reg        1        {depth}
pc_fwd     1        {depth}
pc_bwd     1        {depth}
causal     1        {depth}
unique     1  5     {depth}
liveness   1  9     {live_depth}

[defines]
# Gates the testbench's `assume (reset == $initstate)`.
`define YOSYS
# This core traps on a misaligned load, store or jump target, so the
# aligned-mem instruction models are the ones that describe it.
`define RISCV_FORMAL_ALIGNED_MEM
# The multi-cycle unit's arithmetic replaced by a free value, its sequencer
# left as it is; see the module docstring.
`define RVNTT_ABSTRACT_MULDIV
`define RVNTT_ABSTRACT_BPRED

[verilog-files]
{files}
"""


def cfg_files(rtl_dir):
    """The [verilog-files] list, optionally rebased onto a mirrored RTL tree."""
    base = rtl_dir or ROOT
    return "\n".join([WRAPPER] + [os.path.join(base, p) for p in RTL])


def generate(rtl_dir, verbose):
    """Write the configuration and run genchecks.  Returns the checks dir."""
    os.makedirs(CORE_DIR, exist_ok=True)
    n = write_isa_bundle()
    print("riscv-formal: %s bundle has %d instruction models" % (ISA_BUNDLE, n))
    with open(os.path.join(CORE_DIR, "checks.cfg"), "w") as f:
        f.write(CHECKS_CFG.format(depth=DEPTH, live_depth=LIVENESS_DEPTH,
                                  isa=ISA_BUNDLE, files=cfg_files(rtl_dir)))

    r = subprocess.run([sys.executable, os.path.join(RF, "checks/genchecks.py")],
                       cwd=CORE_DIR, stdout=subprocess.PIPE,
                       stderr=subprocess.STDOUT)
    out = r.stdout.decode("utf-8", "replace")
    if r.returncode != 0:
        print(out)
        raise SystemExit("genchecks.py failed")
    if verbose:
        print(out.rstrip())
    return os.path.join(CORE_DIR, "checks")


def discover(checks_dir):
    return sorted(f[:-4] for f in os.listdir(checks_dir) if f.endswith(".sby"))


def run_check(checks_dir, name):
    """Run one check.  Returns (name, passed, seconds, log tail).

    sby's exit code is not the verdict: genchecks writes `expect pass,fail`
    into every .sby, so a failing proof prints "DONE (FAIL, rc=0)".  The
    verdict comes from the status file, and a missing one is a failure.
    """
    t0 = time.time()
    r = subprocess.run(["sby", "-f", name + ".sby"], cwd=checks_dir,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    out = r.stdout.decode("utf-8", "replace")
    status_path = os.path.join(checks_dir, name, "status")
    try:
        verdict = open(status_path).read().split()[0]
    except (OSError, IndexError):
        verdict = "NO-STATUS"
    if verdict != "PASS":
        out += "\nverdict from %s: %s (sby exit %d)" % (
            os.path.relpath(status_path, ROOT), verdict, r.returncode)
    return name, verdict, time.time() - t0, out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", nargs="+", default=None,
                    help="run only these checks (exact names, or regexes)")
    ap.add_argument("--jobs", "-j", type=int, default=os.cpu_count() or 4)
    ap.add_argument("--list", action="store_true")
    ap.add_argument("-v", "--verbose", action="store_true")
    ap.add_argument("--core-name", default=CORE_NAME,
                    help="riscv-formal cores/<name> working directory. The "
                         "mutation harness gives each parallel worker its own, "
                         "so they cannot overwrite each other's generated "
                         "checks.")
    ap.add_argument("--rtl-dir", default=None,
                    help="read the core from this mirrored RTL tree instead of "
                         "rtl/ (used to fault-inject this harness)")
    a = ap.parse_args()
    global CORE_DIR
    CORE_DIR = os.path.join(RF, "cores", a.core_name)

    if not os.path.isdir(RF):
        print("RVFORMAL_SKIP: toolchain/riscv-formal is not checked out.\n"
              "  git clone https://github.com/YosysHQ/riscv-formal.git \\\n"
              "      toolchain/riscv-formal")
        return 0

    checks_dir = generate(a.rtl_dir, a.verbose)
    names = discover(checks_dir)
    if a.only:
        pats = [re.compile("^(%s)$" % p) for p in a.only]
        names = [n for n in names if any(p.match(n) for p in pats)]

    if a.list:
        for n in names:
            print(n)
        return 0

    # An empty check set is not a pass: genchecks exits 0 with "not supported,
    # skipping instruction checks" when it cannot find the ISA file.
    if not names:
        print("RVFORMAL_FAIL: no checks were generated or selected")
        return 1

    print("=== riscv-formal: %d check(s), depth %d (liveness %d), "
          "muldiv abstracted, %d job(s) ==="
          % (len(names), DEPTH, LIVENESS_DEPTH, a.jobs))
    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=a.jobs) as ex:
        futs = [ex.submit(run_check, checks_dir, n) for n in names]
        for fut in concurrent.futures.as_completed(futs):
            name, verdict, dt, out = fut.result()
            results.append((name, verdict, dt, out))
            print("  %-28s %-9s %6.1fs" % (name, verdict, dt), flush=True)

    results.sort()
    bad = [r for r in results if r[1] != "PASS"]
    # A design Yosys could not read, or a solver that gave up, is a broken
    # experiment rather than a caught bug; tb/mutate/run_mutation.py relies on
    # this exit code to refuse to credit such a mutation.
    broken = [r for r in results if r[1] not in ("PASS", "FAIL")]
    for name, _v, _dt, out in bad:
        print("\n---- %s ----" % name)
        print("\n".join(out.rstrip().splitlines()[-25:]))
    if a.verbose:
        for name, _v, _dt, out in results:
            print("\n---- %s ----" % name)
            print("\n".join(out.rstrip().splitlines()[-8:]))

    total = sum(r[2] for r in results)
    print("\n%d/%d checks passed (%.0fs of solver time across %d job(s))"
          % (len(results) - len(bad), len(results), total, a.jobs))
    if broken:
        print("RVFORMAL_ERROR: " + ", ".join("%s=%s" % (r[0], r[1])
                                             for r in broken))
        return 2
    if bad:
        print("RVFORMAL_FAIL: " + ", ".join(r[0] for r in bad))
        return 1
    print("RVFORMAL_OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
